### ISSUE TITLE
Include subject log comments

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#26]
The most recently shared version of the subject logbook contains entries such as

```yaml
0: 
  subject_id: 0
  public_strain: AML462
  private_strain: AKS471.2.d
  sex: H
  days_on_dex: 1
  growth_stage: L4
  growth_stage_comments: none
  other_comments: none
  multicolor_folder: multicolorworm_20210824_102243
  pump_probe_folder: pumpprobe_20210824_104000
  date: 20210824

1:
  subject_id: 1
  public_strain: AML462
  private_strain: AKS471.2.d
  sex: H
  days_on_dex: 1
  growth_stage: L4
  growth_stage_comments: maybe slightly younger
  other_comments: none
  multicolor_folder: multicolorworm_20210824_114024
  pump_probe_folder: pumpprobe_20210824_114940
  date: 20210824
```

Several comment fields are either `none` (in which case I don't need to include them), or not `none` (in which case I should include them somewhere)

I need to figure out a good place to include this information. Perhaps as a slightly formatted `subject_description`?
